sudo: false
language: python
script: python tools/travis/build.py

after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  git push https://${TOKEN}@github.com/jgraham/css-test-built.git
